### ISSUE TITLE
2.1.20 compatibility?

### ISSUE THREAD

**Issue by ijgnd** [ijgnd/anki21__browser_card_info_bar#3]
@Cupbox reported [here](https://github.com/Arthur-Milchior/anki-enhanced-cloze/issues/18#issuecomment-579335186) the following error message and says that "Disabling Browser Card Info Bar seems to fix it."

```python
Debug info:
Anki 2.1.20 (23f13a31) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=2

Caught exception:
Traceback (most recent call last):
File "aqt\progress.py", line 73, in handler
File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1709973686\cloze_hide_all_21.py", line 419, in newCallback
callback()
File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\2062736101_init_.py", line 222, in newCallback
callback()
File "aqt\browser.py", line 814, in
File "aqt\browser.py", line 833, in _onRowChanged
File "aqt\gui_hooks.py", line 174, in call
File "lib\site-packages\anki\hooks.py", line 451, in runHook
File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\2140680811\infobar.py", line 126, in updateInfoBar
updateInfoBar_default(self)
File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\2140680811\infobar.py", line 147, in updateInfoBar_default
p = self.cardstats(self.card)
File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\2140680811\card_properties.py", line 51, in cardstats
o["Due"] = due_day(card)
File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\2140680811\helper.py", line 24, in due_day
return time.strftime("%Y-%m-%d", time.localtime(mydue))
OSError: [Errno 22] Invalid argument
```

**Comment by ijgnd** [comment]
I can't reproduce the bug

**Comment by Cupbox** [comment]
Here's the addon list
Anki 2.1.20 (23f13a31) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=2

Add-ons:

AMBOSS add-on
Extended Card Stats During Review (disabled)
AnKindle Batch Vocab and Clippings (disabled)
Edit Field During Review (disabled)
TagSelectorV2 (disabled)
Directly review without going through overview page
Auto Markdown (disabled)
Speed Focus Mode auto-alert auto-reveal auto-fail
No Distractions Full Screen (disabled)
Browser Search Box Quick Insert Tag Deck Notetype
GoldenDict Add-On (disabled)
Incremental Reading (disabled)
Multi-field Batch Update
Color Confirmation (disabled)
Special Fields (disabled)
Search in formatted text in any fields
Chinese Support Redux v0130 (disabled)
AnkiDiscord - Discord integration for Anki (disabled)
Extended Tag AddEdit Dialog
  Advanced Review Bottom Bar   (disabled)
Postpone cards review (disabled)
Replay audio from editor (disabled)
Improve speed of change of note type (disabled)
Pretzel Logic Retention Benchmarking
Convert Subdecks to Tag Hierarchy (disabled)
HoochiePapa Randomize New Queue (disabled)
ImageResizer (disabled)
Explain deletions (disabled)
Add Table
Showing time in browser (disabled)
Field History (disabled)
Markdown Support - With Batch n Preview (disabled)
Dict2Anki (disabled)
Localize Media (disabled)
Cacher In The Rye Windows
Quick note and deck buttons Fork for 21
Korean Support (disabled)
Tag Entry Enhancements (disabled)
Image Occlusion Enhanced for Anki 21 alpha
Search and Replace Tags (disabled)
A half-automatic Forvo Downloader (disabled)
load balancer (disabled)
Deck Stats
Simple Timer and Stopwatch for Anki 21 (disabled)
HoochieMama Randomize Rev Queue (disabled)
Symbols
Syntax Highlighting for Code (disabled)
Japanese Pitch Accent
Night Mode (disabled)
Touch Wood Show New Cards Left Hint
Remaining time for Anki 21
GODMODE faster shortcuts and Cloze switching (disabled)
Copy2Clipboard (disabled)
Media Import (disabled)
Cardistry Dynamically Adjust New Cards (disabled)
More Decks Stats and Time Left (disabled)
OpenInExternalEditorRenameDuplicate for ImageAudioVideo (disabled)
Simplified Review GUI (disabled)
Control Audio Playback Pause Skip backwardsforwards Stop Audio (disabled)
Anki Accountability 2 (disabled)
Full Screen Toggle (disabled)
Bulk-Generate Japanese Vocab Frequency Ranking
Advanced Card Styles (disabled)
Kitten Rewards Gamification (disabled)
Doublethink Disables Normalization
MIA Dictionary (disabled)
Content Injector (disabled)
Statistics for Note Types Card Types and Tags
Cloze Hide All
Search EDICT (disabled)
Add tags by shortcuts in Reviewer window one shortcut for one tag (disabled)
 Offline User Manual and Guides en es fr pl ru
Searching PDF Reading  Note-Taking in Add Dialog (disabled)
Incremental Reading 5 - Make Incremental Reading Great Again (disabled)
Backup Key (disabled)
Push Paradox Sibling Cardistry (disabled)
Rebuild All  Empty All for Anki 21
Browser MaximizeHide TableEditor (disabled)
Stats Overview Pie Graph with Distinct Learning and-or Relearning Sections
Large and Colorful Buttons (disabled)
Anki Excel Sync
Zoom 21
HoochieBaby Queue Controller  Day-Lrn Q (disabled)
Update add-ons when collection is synchronized (disabled)
Keep card displayed in reviewer until it is modified
Export deck to HTML (disabled)
Advanced Copy Fields (disabled)
Redesign (disabled)
Study Logger
Ignore accents in browser search
Learning Step and Review Interval Retention
Fastbar another toolbar for Anki 21 beta (disabled)
Sanseido Definitions Python3 Anki21 (disabled)
Export cards selected in the Browser
Audio Files
Customize Sidebar (disabled)
Edit new note type without needing a full sync (disabled)
Visual Feedback Remake Gamification (disabled)
FULLEST SCREEN Hide All Toolbars in Reviewer
If a note has no more card warns instead of deleting it
Add a tag to notes with missing media
remove linebreaks  do word wrap fork for 21 (disabled)
Symbols As You Type
Papercards - export your flashcards to paper (disabled)
Japanese Definition Scraper from weblio Dictionary
AnkiConnect
Enhanced cloze 21
Advanced note editor Multi-column Frozen fields LaTeXs result in editor
Anki Fanfare GamificationFeedback (disabled)
LPCG LyricsPoetry Cloze Generator
Toggle Tags via ReviewerEditorBrowser Context Menu (disabled)
Load Balanced Scheduler
Progress Bar (disabled)
Automatic Basic to Cloze
Alternative Dialog for ReMemorize Touch-Friendly (disabled)
Duplicate Selected Notes (disabled)
Bold the cloze v218
Distinct Cards Studied Today Statistic
AutoDefine - Automatically define vocabulary words with pronunciations and image (disabled)
Browser Card Info Bar (disabled)
Media Internalizer
Highlight Search Results in the Browser (disabled)
Search from Editor for Anki 21 (disabled)
Japanese Example Sentences
Customize Keyboard Shortcuts (disabled)
Quick Colour Changing
Empty cards returns more usable informations (disabled)
SerenityNow (disabled)
Progress Graphs and Stats for Learned and Matured Cards
show new siblings in order  no same day spacingrandomization for new siblings
MIA Japanese (disabled)
Batch Editing
Mini Format Pack (disabled)
Quick tagging 21
Daijirin Dictionary Scraper (disabled)
Anki Welcome Screen (disabled)
Add Hyperlink (disabled)
ReMemorize Rescheduler with sibling and logging v121 (disabled)
Multi-column note editor (disabled)
Opening the same window multiple time (disabled)
Reviewer Context Menu Search (disabled)
Holdem Cardfield Preserves add card history
DrawingPad (disabled)
Edit Field During Review Cloze
Japanese Support
Pop-up Wikipedia Beta (disabled)
Separate Learn and Relearn in the Answer Buttons graph 21
HTML Editor Tweaks v01 (disabled)
Pinyin on top of Hanzi (disabled)
Session Manager (disabled)
AwesomeTTS for Anki 21 updated (disabled)
Throughput Historical (disabled)
SMART SPACEBAR automatic ease scoring (disabled)
Ease Factor Histogram
Replay buttons on card (disabled)
Improving change note type
Frozen Fields (disabled)
Removes Empty Note Types for 21
Improved Quizlet to Anki 21 Importer (disabled)
Fast cards reposition (disabled)
Batch Download Pictures From Google Images (disabled)
add-on dialog searchfilter bar
Blitzkrieg II - Advanced Browser Sidebar BETA5
Anki Killstreaks (disabled)
Vocabulous (disabled)
Stepwise Map Retrieval (disabled)
Japanese Pitch Accent Notes (disabled)
Mouse Wheel Review (disabled)
Pokemanki for both Anki 20 and 21 (disabled)
Numeric Keypad Remapping  ease bugs fixed
Syllabus - Anki Statistics and Export by Tag and Deck (disabled)
deck and card info sidebar during review
Answer Button Sounds
Deck name in title 21 (disabled)
Life Drain
Polar Connect - PDF and Incremental Reading with Anki Sync
More Overview Stats 21
Reset Custom Study Limit Increases
Free Weekend - or Any Other Day (disabled)
FULLER SCREEN Hide Toolbar in Reviewer (disabled)
Additional Card Fields Fork for 21 (disabled)
Change subdecks configuration (disabled)
Small Potatoes Show learning step count in days (disabled)
copy note contents to new Add window from Browser Reviewer Add EditCurrent
Word Query (disabled)
3 add-ons merged quicker anki explain deletion explain database check (disabled)
Increase autosave frequency
Adding note and changing note type become quicker (disabled)
Throughput Monitor (disabled)
Browser TableEditor side-by-side horizontal split
Create Filtered Deck from the Browser
Web Browser - Search terms Import texts and images automatically
Show duplicates (disabled)
Advanced Browser
Enhance main window (disabled)
Slackers Delight PostponeDefer Button (disabled)
Chinese Prestudy (disabled)
Image Search (disabled)
Ze Add note id (disabled)
Kanji Grid (disabled)
Show number of results in browser (disabled)
True Retention by Card Maturity (disabled)
Editor Autocomplete
Japanese Pronunciation  Pitch Accent (disabled)
Incremental Reading v4103 (disabled)
Windows Text Rendering Fix (disabled)
Birl Reinforcement (disabled)
Correct Answers Graph (disabled)
PomodoroTimer
cloze_as_one-master (disabled)
cloze_overlapper
good_riddance
popup_dictionary (disabled)
Puppy Reinforcement (disabled)
Review Heatmap
Subtag Completer (disabled)

After reverting as you mentioned, I could not reproduce the error I had previously been getting.

**Comment by lovac42** [comment]
The problem could be a negative due or odue value from imported or filtered decks. That would explain the exception. Perhapse Cupbox could provide the card info that is causing this issue, that could help narrow it down.

**Comment by ijgnd** [comment]
Applied lovac42's idea in b9caa9fc10117b716a11403de625a2e931ceb603 by wrapping `time.strftime` in a try statement. 

Thanks @lovac42 for helping out and sorry for the late reply.
